# Generated by Django 5.2.3 on 2025-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=40)),
                ('empgender', models.CharField(max_length=10)),
                ('empmobile', models.CharField(max_length=18)),
                ('empusername', models.CharField(max_length=40)),
                ('emppassword', models.CharField(max_length=18)),
            ],
        ),
    ]
