# Generated by Django 5.2.3 on 2025-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=30)),
                ('doc_spe', models.CharField(max_length=40)),
                ('doc_gender', models.CharField(max_length=10)),
                ('doc_mobile', models.CharField(max_length=17)),
                ('doc_age', models.IntegerField()),
            ],
        ),
    ]
