# Generated by Django 5.2.3 on 2025-07-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('pat_id', models.AutoField(primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=30)),
                ('pat_age', models.IntegerField()),
                ('pat_gender', models.CharField(max_length=15)),
                ('pat_address', models.CharField(max_length=50)),
                ('pat_mobile', models.CharField(max_length=17)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.doctors')),
            ],
        ),
    ]
