# Generated by Django 5.2.3 on 2025-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='pat_problem',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
