# Generated by Django 5.2.3 on 2025-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_patients_pat_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
