# Generated by Django 5.2.3 on 2025-07-20 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_doctors_doc_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doc_slots",
            fields=[
                ("slot_id", models.AutoField(primary_key=True, serialize=False)),
                ("slot2", models.TimeField()),
                ("slot3", models.TimeField()),
                ("slot4", models.TimeField()),
                ("slot5", models.TimeField()),
                ("slot6", models.TimeField()),
                ("slot7", models.TimeField()),
                ("slot8", models.TimeField()),
                ("slot9", models.TimeField()),
                ("slot1", models.TimeField()),
                ("slot10", models.TimeField()),
                ("slot11", models.TimeField()),
                ("slot12", models.TimeField()),
                ("slot13", models.TimeField()),
                ("slot14", models.TimeField()),
                ("slot15", models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name="doctors",
            name="slot_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="homepage.doc_slots",
            ),
        ),
    ]
