# Generated by Django 5.2.3 on 2025-07-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_remove_doctors_slot_id_doc_slots_doc_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotsAppointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot1", models.TextField(default="")),
                ("slot2", models.TextField(default="")),
                ("slot3", models.TextField(default="")),
                ("slot4", models.TextField(default="")),
                ("slot5", models.TextField(default="")),
                ("slot6", models.TextField(default="")),
                ("slot7", models.TextField(default="")),
                ("slot8", models.TextField(default="")),
                ("slot9", models.TextField(default="")),
                ("slot10", models.TextField(default="")),
                ("slot11", models.TextField(default="")),
                ("slot12", models.TextField(default="")),
                ("slot13", models.TextField(default="")),
                ("slot14", models.TextField(default="")),
                ("slot15", models.TextField(default="")),
                (
                    "doc_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="homepage.doctors",
                    ),
                ),
                (
                    "slot_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="homepage.doc_slots",
                    ),
                ),
            ],
        ),
    ]
