# Generated by Django 5.2.3 on 2025-07-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_slotsappointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slotsappointments",
            name="slot_id",
        ),
    ]
