# Generated by Django 5.2.3 on 2025-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_remove_slotsappointments_slot_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="slotsappointments",
            name="slot_date",
            field=models.DateField(null=True),
        ),
    ]
